/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Symbol = IDL.Text;
export const Company = IDL.Record({
  'id' : IDL.Nat,
  'pb' : IDL.Float64,
  'pe' : IDL.Float64,
  'eps' : IDL.Float64,
  'roe' : IDL.Float64,
  'debtEquity' : IDL.Float64,
  'revenue' : IDL.Float64,
  'profitGrowth' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'roce' : IDL.Float64,
  'sector' : IDL.Text,
  'low52w' : IDL.Float64,
  'high52w' : IDL.Float64,
  'revenueGrowth' : IDL.Float64,
  'price' : IDL.Float64,
  'dividendYield' : IDL.Float64,
  'symbol' : IDL.Text,
  'netProfit' : IDL.Float64,
  'industry' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LiveQuote = IDL.Record({
  'pe' : IDL.Opt(IDL.Float64),
  'dataSource' : IDL.Text,
  'marketCap' : IDL.Opt(IDL.Float64),
  'lastUpdated' : IDL.Int,
  'low52w' : IDL.Opt(IDL.Float64),
  'high52w' : IDL.Opt(IDL.Float64),
  'change' : IDL.Opt(IDL.Float64),
  'price' : IDL.Opt(IDL.Float64),
  'changePercent' : IDL.Opt(IDL.Float64),
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Financial = IDL.Record({
  'eps' : IDL.Float64,
  'periodType' : IDL.Text,
  'totalAssets' : IDL.Float64,
  'ebitda' : IDL.Float64,
  'revenue' : IDL.Float64,
  'period' : IDL.Text,
  'totalDebt' : IDL.Float64,
  'netProfit' : IDL.Float64,
  'cashFromOperations' : IDL.Float64,
  'companyId' : IDL.Nat,
});
export const User = IDL.Principal;
export const PortfolioEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : User,
  'avgCost' : IDL.Float64,
  'buyDate' : IDL.Text,
  'companyName' : IDL.Text,
  'quantity' : IDL.Float64,
  'symbol' : Symbol,
});
export const Watchlist = IDL.Record({
  'id' : IDL.Nat,
  'symbols' : IDL.Vec(Symbol),
  'userId' : User,
  'name' : IDL.Text,
});
export const ScreenerParams = IDL.Record({
  'maxPB' : IDL.Opt(IDL.Float64),
  'maxPE' : IDL.Opt(IDL.Float64),
  'maxDebtEquity' : IDL.Opt(IDL.Float64),
  'minPB' : IDL.Opt(IDL.Float64),
  'minPE' : IDL.Opt(IDL.Float64),
  'minROCE' : IDL.Opt(IDL.Float64),
  'minROE' : IDL.Opt(IDL.Float64),
  'minMarketCap' : IDL.Opt(IDL.Float64),
  'sector' : IDL.Opt(IDL.Text),
  'maxMarketCap' : IDL.Opt(IDL.Float64),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPortfolioEntry' : IDL.Func(
      [Symbol, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addToWatchlist' : IDL.Func([IDL.Nat, Symbol], [], []),
  'adminAddCompany' : IDL.Func([Company], [], []),
  'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
  'adminListAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWatchlist' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteCompany' : IDL.Func([IDL.Text], [], []),
  'deleteWatchlist' : IDL.Func([IDL.Nat], [], []),
  'fetchLiveQuote' : IDL.Func([IDL.Text], [LiveQuote], []),
  'getAllCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompaniesBySector' : IDL.Func([IDL.Text], [IDL.Vec(Company)], ['query']),
  'getCompany' : IDL.Func([Symbol], [Company], ['query']),
  'getFinancials' : IDL.Func([IDL.Nat], [IDL.Vec(Financial)], ['query']),
  'getSectors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserPortfolio' : IDL.Func([], [IDL.Vec(PortfolioEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserWatchlists' : IDL.Func([], [IDL.Vec(Watchlist)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeFromWatchlist' : IDL.Func([IDL.Nat, Symbol], [], []),
  'removePortfolioEntry' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'screenStocks' : IDL.Func([ScreenerParams], [IDL.Vec(Company)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Symbol = IDL.Text;
  const Company = IDL.Record({
    'id' : IDL.Nat,
    'pb' : IDL.Float64,
    'pe' : IDL.Float64,
    'eps' : IDL.Float64,
    'roe' : IDL.Float64,
    'debtEquity' : IDL.Float64,
    'revenue' : IDL.Float64,
    'profitGrowth' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'roce' : IDL.Float64,
    'sector' : IDL.Text,
    'low52w' : IDL.Float64,
    'high52w' : IDL.Float64,
    'revenueGrowth' : IDL.Float64,
    'price' : IDL.Float64,
    'dividendYield' : IDL.Float64,
    'symbol' : IDL.Text,
    'netProfit' : IDL.Float64,
    'industry' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LiveQuote = IDL.Record({
    'pe' : IDL.Opt(IDL.Float64),
    'dataSource' : IDL.Text,
    'marketCap' : IDL.Opt(IDL.Float64),
    'lastUpdated' : IDL.Int,
    'low52w' : IDL.Opt(IDL.Float64),
    'high52w' : IDL.Opt(IDL.Float64),
    'change' : IDL.Opt(IDL.Float64),
    'price' : IDL.Opt(IDL.Float64),
    'changePercent' : IDL.Opt(IDL.Float64),
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Financial = IDL.Record({
    'eps' : IDL.Float64,
    'periodType' : IDL.Text,
    'totalAssets' : IDL.Float64,
    'ebitda' : IDL.Float64,
    'revenue' : IDL.Float64,
    'period' : IDL.Text,
    'totalDebt' : IDL.Float64,
    'netProfit' : IDL.Float64,
    'cashFromOperations' : IDL.Float64,
    'companyId' : IDL.Nat,
  });
  const User = IDL.Principal;
  const PortfolioEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : User,
    'avgCost' : IDL.Float64,
    'buyDate' : IDL.Text,
    'companyName' : IDL.Text,
    'quantity' : IDL.Float64,
    'symbol' : Symbol,
  });
  const Watchlist = IDL.Record({
    'id' : IDL.Nat,
    'symbols' : IDL.Vec(Symbol),
    'userId' : User,
    'name' : IDL.Text,
  });
  const ScreenerParams = IDL.Record({
    'maxPB' : IDL.Opt(IDL.Float64),
    'maxPE' : IDL.Opt(IDL.Float64),
    'maxDebtEquity' : IDL.Opt(IDL.Float64),
    'minPB' : IDL.Opt(IDL.Float64),
    'minPE' : IDL.Opt(IDL.Float64),
    'minROCE' : IDL.Opt(IDL.Float64),
    'minROE' : IDL.Opt(IDL.Float64),
    'minMarketCap' : IDL.Opt(IDL.Float64),
    'sector' : IDL.Opt(IDL.Text),
    'maxMarketCap' : IDL.Opt(IDL.Float64),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPortfolioEntry' : IDL.Func(
        [Symbol, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addToWatchlist' : IDL.Func([IDL.Nat, Symbol], [], []),
    'adminAddCompany' : IDL.Func([Company], [], []),
    'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
    'adminListAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWatchlist' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteCompany' : IDL.Func([IDL.Text], [], []),
    'deleteWatchlist' : IDL.Func([IDL.Nat], [], []),
    'fetchLiveQuote' : IDL.Func([IDL.Text], [LiveQuote], []),
    'getAllCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompaniesBySector' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Company)],
        ['query'],
      ),
    'getCompany' : IDL.Func([Symbol], [Company], ['query']),
    'getFinancials' : IDL.Func([IDL.Nat], [IDL.Vec(Financial)], ['query']),
    'getSectors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserPortfolio' : IDL.Func([], [IDL.Vec(PortfolioEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserWatchlists' : IDL.Func([], [IDL.Vec(Watchlist)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeFromWatchlist' : IDL.Func([IDL.Nat, Symbol], [], []),
    'removePortfolioEntry' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'screenStocks' : IDL.Func([ScreenerParams], [IDL.Vec(Company)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };