/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Company {
  'id' : bigint,
  'pb' : number,
  'pe' : number,
  'eps' : number,
  'roe' : number,
  'debtEquity' : number,
  'revenue' : number,
  'profitGrowth' : number,
  'marketCap' : number,
  'name' : string,
  'roce' : number,
  'sector' : string,
  'low52w' : number,
  'high52w' : number,
  'revenueGrowth' : number,
  'price' : number,
  'dividendYield' : number,
  'symbol' : string,
  'netProfit' : number,
  'industry' : string,
}
export interface Financial {
  'eps' : number,
  'periodType' : string,
  'totalAssets' : number,
  'ebitda' : number,
  'revenue' : number,
  'period' : string,
  'totalDebt' : number,
  'netProfit' : number,
  'cashFromOperations' : number,
  'companyId' : bigint,
}
export interface LiveQuote {
  'pe' : [] | [number],
  'dataSource' : string,
  'marketCap' : [] | [number],
  'lastUpdated' : bigint,
  'low52w' : [] | [number],
  'high52w' : [] | [number],
  'change' : [] | [number],
  'price' : [] | [number],
  'changePercent' : [] | [number],
  'symbol' : string,
}
export interface PortfolioEntry {
  'id' : bigint,
  'userId' : User,
  'avgCost' : number,
  'buyDate' : string,
  'companyName' : string,
  'quantity' : number,
  'symbol' : Symbol,
}
export interface ScreenerParams {
  'maxPB' : [] | [number],
  'maxPE' : [] | [number],
  'maxDebtEquity' : [] | [number],
  'minPB' : [] | [number],
  'minPE' : [] | [number],
  'minROCE' : [] | [number],
  'minROE' : [] | [number],
  'minMarketCap' : [] | [number],
  'sector' : [] | [string],
  'maxMarketCap' : [] | [number],
}
export type Symbol = string;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type User = Principal;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Watchlist {
  'id' : bigint,
  'symbols' : Array<Symbol>,
  'userId' : User,
  'name' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioEntry' : ActorMethod<
    [Symbol, string, number, number, string],
    bigint
  >,
  'addToWatchlist' : ActorMethod<[bigint, Symbol], undefined>,
  'adminAddCompany' : ActorMethod<[Company], undefined>,
  'adminDeleteUser' : ActorMethod<[Principal], undefined>,
  'adminListAllUsers' : ActorMethod<[], Array<Principal>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWatchlist' : ActorMethod<[string], bigint>,
  'deleteCompany' : ActorMethod<[string], undefined>,
  'deleteWatchlist' : ActorMethod<[bigint], undefined>,
  'fetchLiveQuote' : ActorMethod<[string], LiveQuote>,
  'getAllCompanies' : ActorMethod<[], Array<Company>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompaniesBySector' : ActorMethod<[string], Array<Company>>,
  'getCompany' : ActorMethod<[Symbol], Company>,
  'getFinancials' : ActorMethod<[bigint], Array<Financial>>,
  'getSectors' : ActorMethod<[], Array<string>>,
  'getUserPortfolio' : ActorMethod<[], Array<PortfolioEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'getUserWatchlists' : ActorMethod<[], Array<Watchlist>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'removeFromWatchlist' : ActorMethod<[bigint, Symbol], undefined>,
  'removePortfolioEntry' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'screenStocks' : ActorMethod<[ScreenerParams], Array<Company>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateUserProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];