/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScreenerParams {
    maxPB?: number;
    maxPE?: number;
    maxDebtEquity?: number;
    minPB?: number;
    minPE?: number;
    minROCE?: number;
    minROE?: number;
    minMarketCap?: number;
    sector?: string;
    maxMarketCap?: number;
}
export type Symbol = string;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type User = Principal;
export interface LiveQuote {
    pe?: number;
    dataSource: string;
    marketCap?: number;
    lastUpdated: bigint;
    low52w?: number;
    high52w?: number;
    change?: number;
    price?: number;
    changePercent?: number;
    symbol: string;
}
export interface Watchlist {
    id: bigint;
    symbols: Array<Symbol>;
    userId: User;
    name: string;
}
export interface Company {
    id: bigint;
    pb: number;
    pe: number;
    eps: number;
    roe: number;
    debtEquity: number;
    revenue: number;
    profitGrowth: number;
    marketCap: number;
    name: string;
    roce: number;
    sector: string;
    low52w: number;
    high52w: number;
    revenueGrowth: number;
    price: number;
    dividendYield: number;
    symbol: string;
    netProfit: number;
    industry: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface Financial {
    eps: number;
    periodType: string;
    totalAssets: number;
    ebitda: number;
    revenue: number;
    period: string;
    totalDebt: number;
    netProfit: number;
    cashFromOperations: number;
    companyId: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PortfolioEntry {
    id: bigint;
    userId: User;
    avgCost: number;
    buyDate: string;
    companyName: string;
    quantity: number;
    symbol: Symbol;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPortfolioEntry(symbol: Symbol, companyName: string, quantity: number, avgCost: number, buyDate: string): Promise<bigint>;
    addToWatchlist(watchlistId: bigint, symbol: Symbol): Promise<void>;
    adminAddCompany(company: Company): Promise<void>;
    adminDeleteUser(user: Principal): Promise<void>;
    adminListAllUsers(): Promise<Array<Principal>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createWatchlist(name: string): Promise<bigint>;
    deleteCompany(symbol: string): Promise<void>;
    deleteWatchlist(watchlistId: bigint): Promise<void>;
    fetchLiveQuote(symbol: string): Promise<LiveQuote>;
    getAllCompanies(): Promise<Array<Company>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompaniesBySector(sector: string): Promise<Array<Company>>;
    getCompany(symbol: Symbol): Promise<Company>;
    getFinancials(companyId: bigint): Promise<Array<Financial>>;
    getSectors(): Promise<Array<string>>;
    getUserPortfolio(): Promise<Array<PortfolioEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(): Promise<UserRole>;
    getUserWatchlists(): Promise<Array<Watchlist>>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(name: string, email: string): Promise<void>;
    removeFromWatchlist(watchlistId: bigint, symbol: Symbol): Promise<void>;
    removePortfolioEntry(entryId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    screenStocks(params: ScreenerParams): Promise<Array<Company>>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateUserProfile(newName: string, newEmail: string): Promise<void>;
}
import type { LiveQuote as _LiveQuote, ScreenerParams as _ScreenerParams, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPortfolioEntry(arg0: Symbol, arg1: string, arg2: number, arg3: number, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortfolioEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortfolioEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addToWatchlist(arg0: bigint, arg1: Symbol): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0, arg1);
            return result;
        }
    }
    async adminAddCompany(arg0: Company): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddCompany(arg0);
            return result;
        }
    }
    async adminDeleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0);
            return result;
        }
    }
    async adminListAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllUsers();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createWatchlist(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWatchlist(arg0);
            return result;
        }
    }
    async deleteCompany(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCompany(arg0);
            return result;
        }
    }
    async deleteWatchlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWatchlist(arg0);
            return result;
        }
    }
    async fetchLiveQuote(arg0: string): Promise<LiveQuote> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchLiveQuote(arg0);
                return from_candid_LiveQuote_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchLiveQuote(arg0);
            return from_candid_LiveQuote_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCompanies(): Promise<Array<Company>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCompanies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCompanies();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompaniesBySector(arg0: string): Promise<Array<Company>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompaniesBySector(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompaniesBySector(arg0);
            return result;
        }
    }
    async getCompany(arg0: Symbol): Promise<Company> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompany(arg0);
            return result;
        }
    }
    async getFinancials(arg0: bigint): Promise<Array<Financial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancials(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancials(arg0);
            return result;
        }
    }
    async getSectors(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectors();
            return result;
        }
    }
    async getUserPortfolio(): Promise<Array<PortfolioEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPortfolio();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWatchlists(): Promise<Array<Watchlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWatchlists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWatchlists();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async removeFromWatchlist(arg0: bigint, arg1: Symbol): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0, arg1);
            return result;
        }
    }
    async removePortfolioEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePortfolioEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePortfolioEntry(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async screenStocks(arg0: ScreenerParams): Promise<Array<Company>> {
        if (this.processError) {
            try {
                const result = await this.actor.screenStocks(to_candid_ScreenerParams_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.screenStocks(to_candid_ScreenerParams_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_LiveQuote_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveQuote): LiveQuote {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pe: [] | [number];
    dataSource: string;
    marketCap: [] | [number];
    lastUpdated: bigint;
    low52w: [] | [number];
    high52w: [] | [number];
    change: [] | [number];
    price: [] | [number];
    changePercent: [] | [number];
    symbol: string;
}): {
    pe?: number;
    dataSource: string;
    marketCap?: number;
    lastUpdated: bigint;
    low52w?: number;
    high52w?: number;
    change?: number;
    price?: number;
    changePercent?: number;
    symbol: string;
} {
    return {
        pe: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pe)),
        dataSource: value.dataSource,
        marketCap: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.marketCap)),
        lastUpdated: value.lastUpdated,
        low52w: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.low52w)),
        high52w: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.high52w)),
        change: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.change)),
        price: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.price)),
        changePercent: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.changePercent)),
        symbol: value.symbol
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_ScreenerParams_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScreenerParams): _ScreenerParams {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxPB?: number;
    maxPE?: number;
    maxDebtEquity?: number;
    minPB?: number;
    minPE?: number;
    minROCE?: number;
    minROE?: number;
    minMarketCap?: number;
    sector?: string;
    maxMarketCap?: number;
}): {
    maxPB: [] | [number];
    maxPE: [] | [number];
    maxDebtEquity: [] | [number];
    minPB: [] | [number];
    minPE: [] | [number];
    minROCE: [] | [number];
    minROE: [] | [number];
    minMarketCap: [] | [number];
    sector: [] | [string];
    maxMarketCap: [] | [number];
} {
    return {
        maxPB: value.maxPB ? candid_some(value.maxPB) : candid_none(),
        maxPE: value.maxPE ? candid_some(value.maxPE) : candid_none(),
        maxDebtEquity: value.maxDebtEquity ? candid_some(value.maxDebtEquity) : candid_none(),
        minPB: value.minPB ? candid_some(value.minPB) : candid_none(),
        minPE: value.minPE ? candid_some(value.minPE) : candid_none(),
        minROCE: value.minROCE ? candid_some(value.minROCE) : candid_none(),
        minROE: value.minROE ? candid_some(value.minROE) : candid_none(),
        minMarketCap: value.minMarketCap ? candid_some(value.minMarketCap) : candid_none(),
        sector: value.sector ? candid_some(value.sector) : candid_none(),
        maxMarketCap: value.maxMarketCap ? candid_some(value.maxMarketCap) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
